version: "3.8"

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: realstate
    ports:
      - "5438:5432"
    container_name: RealstateDB
    volumes:
      - ./postgres:/var/lib/postgresql/data